#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry “TestMenuEntry 2018-06-16T2347+0600” {
loopback loop (hd0,5)
linux (loop)/casper/vmlinuz.efi boot=casper quiet splash
initrd (loop)/casper/initrd.lz

}
